import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import BlogPostItem from "../components/blogPostItem";
import Layout from "../components/layout";
import { getAllFilledPosts } from "../utils/wordpress";
import HeroPost from "../components/heroPost";
import Pagination from "../components/pagination";

interface HomeProps {
  stickyPost?: object;
  nonStickyPosts?: object;
  header?: any;
}

export default function Home({
  stickyPost,
  nonStickyPosts,
  header,
}: HomeProps) {
  console.log(header);

  return (
    <Layout>
      <Head>
        <title>Thepeer&#39;s Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="blog">
        <HeroPost post={stickyPost} />
        <section aria-labelledby="articles">
          <div className="blog__articles">
            <h2 id="articles" className="blog__articles__header">
              See more articles
            </h2>
            <div className="blog__articles__grid">
              {nonStickyPosts.map((post: object, index: number) => (
                <BlogPostItem key={index} data={post} />
              ))}
            </div>
            <Pagination />
          </div>
        </section>
      </div>
    </Layout>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const allPosts = await getAllFilledPosts();

  const stickyPost = allPosts.filledPost[0];
  const nonStickyPosts = allPosts.filledPost.slice(1);

  return {
    props: {
      stickyPost,
      nonStickyPosts,
      header: allPosts.headers,
    },
  };
};
